# Generated by Django 5.0.1 on 2024-01-15 13:09

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(max_length=3500, verbose_name="Вопрос"),
                ),
                (
                    "answer",
                    models.TextField(max_length=1500, verbose_name="Ответ"),
                ),
                (
                    "handout",
                    models.TextField(
                        blank=True,
                        max_length=3500,
                        null=True,
                        verbose_name="Раздатка",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=4500,
                        null=True,
                        verbose_name="Коментарий",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        upload_to="images/", verbose_name="Фотографии"
                    ),
                ),
                (
                    "audio",
                    models.FileField(upload_to="audio/", verbose_name="Аудио"),
                ),
                (
                    "correct_answers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Правельные ответы"
                    ),
                ),
                (
                    "incorrect_answers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Неправельные ответы"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 16, 16, 9, 56, 755251
                        )
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
