# Generated by Django 5.0.1 on 2024-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="questions",
            new_name="championship",
        ),
        migrations.AlterField(
            model_name="author",
            name="city",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Город автора"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.TextField(max_length=100, verbose_name="Имя автора"),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.TextField(max_length=100, verbose_name="Фамилия автора"),
        ),
        migrations.AlterField(
            model_name="championship",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата игры"),
        ),
    ]
