# Generated by Django 5.0.1 on 2024-01-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_rename_questions_question_championship_and_more"),
        ("users", "0002_name_alter_city_city_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_author",
                to="users.name",
                verbose_name="Автор вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="championship",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="championship_author",
                to="users.name",
                verbose_name="Автор чемпионата",
            ),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
    ]
