# Generated by Django 5.0.1 on 2024-01-15 19:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_alter_questionuser_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionuser",
            name="create",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 16, 22, 25, 42, 198893)
            ),
        ),
    ]
