# Generated by Django 5.0.1 on 2024-01-17 15:15

import datetime

import django.db.models.deletion
from django.db import migrations, models

import questions.validators


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0004_alter_questionuser_create"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="audio/",
                validators=[questions.validators.validate_is_audio],
                verbose_name="Аудио",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="Фотографии",
            ),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="create",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 18, 15, 57, 80343)
            ),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="questions.question",
            ),
        ),
    ]
