# Generated by Django 5.0.1 on 2024-01-19 09:04

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "questions",
            "0007_remove_questionuser_id_alter_questionuser_create_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionuser",
            name="create",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 12, 4, 31, 410207)
            ),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_user",
                to="questions.question",
            ),
        ),
        migrations.AlterField(
            model_name="questionuser",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="question_user",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
